version:  '3.7'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
     POSTGRES_DB: web_vc_rest
     POSTGRES_PASSWORD: kataPassword
     POSTGRES_USER: Raids
     PGDATA: /var/lib/postgresql/data

  rest_vc_web:
    image: web_vc_rest:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/web_vc_rest
      - SPRING_DATASOURCE_USERNAME=Raids
      - SPRING_DATASOURCE_PASSWORD=kataPassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin